ibm_cloud_fail_over/__init__.py,sha256=Ch7tEJbrkiD5ip7BpGVcPBUKVy7956G6vSHtJufiQds,682
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=tjU7JI5u9Egz3iXQ6Zfyv7tqiSxUlHS2epaHsHHwOzs,51252
ibm_cloud_fail_over-1.0.21.dist-info/METADATA,sha256=wGVQP4J35_phX3y3-QhE662oIXGppz_3IApKbW3ikzk,10786
ibm_cloud_fail_over-1.0.21.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-1.0.21.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-1.0.21.dist-info/RECORD,,
